package viteezy.domain;

public enum LoggingEvent {
    CUSTOMER_LOGGED_IN,
    PAYMENT_PLAN_REACTIVATED,
    PAYMENT_PLAN_PAUSED,
    PAYMENT_PLAN_STOPPED,
    PAYMENT_PLAN_CANCELED,
    PAYMENT_PLAN_UPDATED,
    INGREDIENT_ADDED,
    INGREDIENT_REMOVED,
    INGREDIENT_UPDATED
}
