server {
  listen 3000;
  server_name viteezy;
  root /usr/share/nginx/html;
  index index.html;
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";

  gzip on;
  gzip_proxied any;
  gzip_types text/css application/javascript;
  gzip_min_length 1000;

  location / {
    try_files $uri $uri/ /index.html =404;
  }

  location /blog {
    proxy_ssl_server_name on;
    proxy_pass https://blog.viteezy.nl/;
  }

  location /assets {
    expires 1y;
    add_header Cache-Control "public";
  }

  location ~*  \.(js|css|woff)$ {
    expires 1y;
    add_header Cache-Control "public";
    add_header Access-Control-Allow-Origin "*";
  }
}