version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  vit_tool:
    image: viteezyorderprocessing:latest
    command: vop process run --all
    network_mode: host

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - MYSQL_DATABASE=viteezy
      - MYSQL_USER=vit_tool
      - MYSQL_PASSWORD=secure_password
    volumes:
      - ./docker/development/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
    ports:
      - 3306:3306
    restart: unless-stopped
  sftp_server:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22"
    command: foo::1001::PDF
    volumes:
      - ./docker/development/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./docker/development/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./docker/development/ssh_client_rsa_key.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
volumes:
  vop_data: