apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: viteezy-local
  labels:
    app: frontend
spec:
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: viteezy-local
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      namespace: viteezy-local
    spec:
      imagePullSecrets:
        - name: my-ecr-secret
      terminationGracePeriodSeconds: 120
      containers:
        - name: frontend
          image: 364293105208.dkr.ecr.eu-west-1.amazonaws.com/viteezy_frontend:${frontend}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
