apiVersion: batch/v1
kind: CronJob
metadata:
  name: post-nl-shipment-status
  namespace: viteezy-production
spec:
  schedule: "6 9-19 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: alpine-httpie-pharmacist-request
              image: alpine/httpie:2.2.0
              command:
                - http
                - "POST"
                - "backend:8081/tasks/post-nl-shipment-status"
                - "--ignore-stdin"
                - "--check-status"
          restartPolicy: Never