apiVersion: batch/v1
kind: CronJob
metadata:
  name: order-pdf-processing
  namespace: viteezy-staging
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: docker-order-pdf-processing
              image: europe-docker.pkg.dev/viteezy/order-pdf-processing/docker:latest
              command:
                - /bin/sh
                - -c
                - vop process run --all
              env:
                - name: DATABASE_HOST
                  value: db-backend-service
                - name: DATABASE_USERNAME
                  value: viteezyUser
                - name: DATABASE_PASSWORD
                  value: canned-juggling-discard-bronze-purchase-wannabe
                - name: SFTP_HOST
                  value: sftp-gateway-transfer.a16.cldsvc.net
                - name: SFTP_USERNAME
                  value: sftpviteezya
                - name: SFTP_PRIVATE_KEY
                  value: /etc/viteezy-staging-secret-volume/private_key_viteezy_accp.pem
                - name: STRAPI_HOST
                  value: https://staging-cms.viteezy.com
                - name: STRAPI_ACCESS_TOKEN
                  value: 3790d16ab987f737c4c0053f549601f391d19bc773178b1bc0950e6d243507fee2dfc07d74087332cd59b4391026e07822a14d16b88abd9c5cdbbd28a19841b17f0501a92fe621a95548637eac7b428d9d1e22865d10080bb65714eca5193b97e45dae4266ab2c685c022d66c819c79451dacb24a7e4d38e606a6b6e4b8ac9b7
              volumeMounts:
                - name: viteezy-staging-secret-volume
                  readOnly: true
                  mountPath: "/etc/viteezy-staging-secret-volume"
          volumes:
          - name: viteezy-staging-secret-volume
            secret:
              secretName: viteezy-staging-secrets
          restartPolicy: Never